config/routes.rb
Rails.application.routes.draw do
  root "home#show"
  get '/about', to: "home#about", as: "about"
  resources :issues
  resources :repositories
  resources :users
  delete "/logout", to: "sessions#destroy", as: "logout"
  get '/auth/:provider/callback', to: "sessions#create"
  post '/webhooks/receive', to: "webhooks#receive"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :repository
  delegate :user, to: :repository
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
  has_many :issues

  include ActiveModel::Validations
  validates_with RepositoryValidator
  validates :url, uniqueness: true, presence: true, format: {with: /https:\/\/github.com/, message: "must be a valid github url"}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :repositories
  has_many :issues, through: :repositories
  before_save :normalize_phone_number
  # validates :url, uniqueness: true, presence: true, format: {with: /https:\/\/github.com/, message: "must be a valid github url"}

  validates :phone_number, format: {with: /\d{3}-\d{3}-\d{4}/}, allow_nil: true

  def self.find_or_create_from_omniauth(auth)
    User.find_or_create_by(github_uid: auth["uid"]).tap do |u|
      u.github_username = auth["info"]["nickname"]
      u.email = auth["info"]["email"]
      u.avatar_url = auth["info"]["image"]
      u.name = auth["info"]["name"]
      u.save
    end
  end

  def display_phone_number
    phone_number && !phone_number.empty? ? phone_number : "<i>add your phone number to receive text message updates</i>".html_safe
  end

  def normalize_phone_number
    if phone_number && phone_number.strip.empty?
      phone_number = nil 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate
  helper_method :logged_in?, :current_user, :authenticate, :log_in

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def authenticate
    redirect_to root_path unless logged_in?
  end
end

app/controllers/github_webhooks_controller.rb
class GithubWebhooksController < ApplicationController

  include GithubWebhook::Processor

  # Handle push event
  def github_push(payload)
    # TODO: handle push webhook
  end

  # Handle create event
  def github_create(payload)
    # TODO: handle create webhook
  end

  private

  def webhook_secret(payload)
    ENV['GITHUB_SECRET']
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate

  def show
  end

  def about
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def index
    @issues = current_user.issues
  end

  def show
    @issue = Issue.find(params[:id])
    if @issue.user == current_user
      render :show
    else
      redirect_to root_path, notice: "you can only view your own issues!"
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    @repositories = current_user.repositories
  end

  def show
    @repository = Repository.find(params[:id])
    if @repository.user == current_user
      render :show
    else
      redirect_to root_path, notice: "you can only view your own repos!"
    end
  end

  def create
    @client ||= Octokit::Client.new(access_token: ENV["GITHUB_TOKEN"])
    repo_owner = params[:repository][:url].split("/")[-2]
    repo_name = params[:repository][:url].split("/")[-1]
    @repo = Repository.new(name: repo_name, url: params[:repository][:url], user: current_user)
    if @repo.save
      gh_repo = @client.repo("#{repo_owner}/#{repo_name}")
      @client.issues("#{repo_owner}/#{repo_name}").each do |issue|
        Issue.create(url: issue.html_url, opened_by: issue.user.login, status: issue.state, title: issue.title, content: issue.body, opened_on: issue.created_at, assignee: issue.assignee, repository: @repo)
      end
      @client.create_hook("#{repo_owner}/#{repo_name}",
        'web',
        {url: "#{ENV['ISSUE_TRACKR_APP_URL']}/webhooks/receive", content_type: 'json'},
        {events: ['issues'], active: true})
    end
    respond_to do |f|
      f.js
      f.html {head :no_content; return}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate
  
  def create
    user = User.find_or_create_from_omniauth(auth_params)
    if user
      log_in(user)
      redirect_to user_path(user)
    else
      redirect_to root_path, notice: "could not be authenticated with GitHub"
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private 

    def auth_params
      request.env["omniauth.auth"]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:update]

  def show
    @user = current_user
  end

  def update
    if @user == current_user
      @user.phone_number = user_params[:phone_number]
      if @user.save
        respond_to do |f|
          f.js
        end
      else
        respond_to do |f|
          f.js {render 'phone_errors.js.erb'}
        end
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:phone_number)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController

  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate

  def receive
    if params[:zen]
      head :no_content
      return
    else
      issue = Issue.find_or_create_by(url: issue_params["html_url"])
      if !issue.repository
        url_elements= issue_params["repository_url"].split("/")
        repo_url = "https://github.com/#{url_elements[-2]}/#{url_elements[-1]}"
        repo = Repository.find_by(url: repo_url)
        issue.update(repository: repo)
      end
      issue.update(title: issue_params["title"], content: issue_params["body"], assignee: issue_params["assignee"], status: issue_params["state"])
      owner = issue.repository.user
      # if owner.phone_number
      #   @client = Twilio::REST::Client.new(ENV['TWILIO_SID'], ENV['TWILIO_TOKEN'])
      #   @client.messages.create(
      #     to: owner.phone_number,
      #     from: "+1 #{ENV['TWILIO_NUMBER']}",
      #      body: "#{issue.title} has been updated. View it here: #{issue.url}")
      # end
      UserMailer.issue_update_email(issue.user, issue).deliver_now
      head :no_content
      return
    end
  end

  private

    def issue_params
      params["issue"]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_webhooks_helper.rb
module GithubWebhooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About</h1>

<p>This project is maintained by <a href="http://www.sophiedebenedetto.nyc">Sophie DeBenedtto.</a> </p>

<p>You can view the source code <a href="https://github.com/sophiedebenedetto/flatiron-issue-trackr">here</a></p>

app/views/home/show.html.erb
<div class="jumbotron">
  <h1>Welcome to Issue Trackr</h1>
  <p>add your GitHub repo and start tracking your issues!</p>
  <p>receive emails and texts when an issue has been opened, changed or closed on one of your repos</p>
</div>
<footer class="panel-footer navbar navbar-fixed-bottom">
  <p>Made with <3 at the Flatiron School | <a href="/about">about</a></p>
</footer>

app/views/issues/_issue.html.erb
<div data-show="issue" data-issue-repo="<%=issue.repository.id%>">
  <%=link_to issue.title, issue_path(issue)%>
</div>

app/views/issues/index.html.erb
<h1>Your Issues</h1>

<ul>
   <%@issues.each do |issue|%>
   <div class="panel panel-default">
      <div class="panel-heading">
         <h3 class="panel-title"><%=link_to issue.title, issue_path(issue)%></h3>
      </div>
      <div class="panel-body">
        <p><strong>repo:</strong> <%=issue.repository.name.gsub("-", " ").capitalize%></p>
        <p><strong>assignee:</strong> <%=issue.assignee || 'n/a'%></p>
        <p><%=link_to "view on github", issue.url%></p>
      </div>
    </div>
   <%end%>
</ul>

app/views/issues/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
     <h3 class="panel-title"><%=@issue.title%></h3>
  </div>
  <div class="panel-body">
    <p><strong>repo:</strong> <%=@issue.repository.name.gsub("-", " ").titleize%></p>
    <p><strong>assignee:</strong> <%=@issue.assignee || 'n/a'%></p>
    <p><strong>opened at:</strong> <%=@issue.opened_on%></p>
    <p><strong>opened by:</strong> <%=@issue.opened_by%></p>
    <p><strong>content: </strong><%=@issue.content%></p>
    <p><%=link_to "view on github", @issue.url%></p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "// Issue Trackr", root_path, class: "navbar-brand"%>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li>
           <%= link_to "issues", issues_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="<%=current_user.avatar_url%>" id="nav-bar-avatar"/></a>
            <ul class="dropdown-menu">
              <li><%= link_to "log out", logout_path, method: "delete" %></li>
              <li><%= link_to "profile", user_path(current_user) %></li>
            </ul>
        </ul>
      <%else%>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "log in", '/auth/github'%>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubIssueTrackr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar'%>
  <div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/repositories/_errors.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">could not save repo! <span class="glyphicon glyphicon-remove-sign" id="close-repo-error-panel" data-panel="close"></span></h3>
  </div>
   <div class="panel-body">
    <%errors.each do |type, messages|%> 
      <%messages.each do |msg| %>
        <p style="margin-left: 3%; margin-top: 1%;"><span class="glyphicon glyphicon-warning-sign"></span> <%=msg%></p>
      <%end%>
    <%end%>
  </div>
</div>

app/views/repositories/_modal.html.erb
<a href="#" data-toggle="modal" data-target="#myModal" id="new_repo_modal" class="btn btn-primary">+ repository</a>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">add a new repo</h4>
      </div>
      <div class="modal-body">
        <%= render 'repositories/new', {repository: Repository.new} %>
      </div>
      <div class="modal-footer">
       <button type="submit" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/repositories/_new.html.erb
<%=form_for repository, remote: true do |f| %>
 url
  <%=f.text_field :url, id: "repo-input"%>
  <%=f.submit "+", class: "btn btn-primary"%>
<%end%>

app/views/repositories/_repo.html.erb
<li class="list-group-item">
  <span class="badge" data-repo="<%=repo.id%>" id="issue-count"><%=repo.issues.count%></span>
  <strong><%=repo.name.gsub("-", " ").capitalize %></strong>
    <%= render partial: "issues/issue", collection: repo.issues%>
</li>

app/views/repositories/_repos.html.erb
<ul class="list-group" data-id="repo-list-items">
  <%repositories.each do |repo|%>
    <%= render partial: "repositories/repo", locals: {repo: repo}%>
  <%end%>
</ul>

app/views/repositories/create.js.erb
$("input#repo-input").val(" ")
$("#myModal").modal("toggle")
<% if !@repo.valid?%>
  $("#errors").html("<%= j render(partial: 'repositories/errors', locals: {errors: @repo.errors.messages})%>")
<%else%>
  $("#errors").html(" ")
  $("ul[data-id='repo-list-items']").append("<%= j render(partial: 'repositories/repo', locals: {repo: @repo})%>")
<%end%>

app/views/users/_phone_number.html.erb
phone: <%=user.display_phone_number%>      <span class="glyphicon glyphicon-pencil" data-select="phone-edit"></span>

app/views/users/phone_errors.js.erb
$("[data-id='phone-number']").html("<p>phone: <i>phone number must be in xxx-xxx-xxxx format</i>   <span class='glyphicon glyphicon-pencil' data-select='phone-edit'></span>")

app/views/users/show.html.erb
<div class="jumbotron profile">
  <h1 id="profile-name"><image src="<%=@user.avatar_url%>" id="profile-avatar"> Hi, <%=@user.name%></h1>
  <p>github username: <%=link_to @user.github_username, "https://github.com/#{@user.github_username}", target: "blank"%></p>
  <p>email: <%=@user.email%></p>
  <p data-id="phone-number" data-user="<%=@user.id%>" data-select="phone-edit-parent">
    <%= render partial: "users/phone_number", locals: {user: @user}%>
  </p>
</div>

<div style="text-align: center; margin-bottom: 2%;">
  <%=render partial: 'repositories/modal'%>
</div>
 
<div data-id="repo-list">
  <%= render partial: "repositories/repos", locals: {repositories: @user.repositories}%>
</div>
<div id="errors" style="margin-bottom: 5%">
</div>

app/views/users/update.js.erb
$("[data-id='phone-number']").html("<%= j render partial: 'users/phone_number', locals: {user: @user}%>");